default:
  image-id: ami-cef405a7
  size: large
  inbound-ports: [22, 80, 443, 8080, 8443]
  provision: none

build-image:
  image-id: ami-1aad5273
  size: large
  inbound-ports: [22, 80, 443, 8080, 8443]
  provision: none